version: '3.3'
services:
   n8n:
      container_name: pdf-service-n8n
      image: n8nio/n8n:latest
      environment:
         - N8N_RUNNERS_AVAILABLE=true
         - N8N_BASIC_AUTH_ACTIVE=true
         - N8N_BASIC_AUTH_USER=root
         - N8N_BASIC_AUTH_PASSWORD=password
         - N8N_PORT=5678
         - N8N_PROTOCOL=http
         - N8N_HOST=localhost
         - N8N_SECURE_COOKIE=false
         - WEBHOOK_URL=http://localhost:5678
         - N8N_WEBHOOK_URL=http://localhost:5678
         - DB_TYPE=postgresdb
         - DB_POSTGRESDB_HOST=pdf-service-postgres
         - DB_POSTGRESDB_PORT=5432
         - DB_POSTGRESDB_DATABASE=n8n
         - DB_POSTGRESDB_USERNAME=postgres
         - DB_POSTGRESDB_PASSWORD=toor
         - N8N_ENCRYPTION_KEY=tutu
      ports:
         - "5678:5678"
      depends_on:
         - postgres
   postgres:
      container_name: pdf-service-postgres
      tty: true
      image: postgres:17
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=toor
         - POSTGRES_DB=n8n
   ministack:
      image: ministackorg/ministack:latest
      container_name: pdf-service-ministack
      ports:
         - "4566:4566"
      environment:
         - SERVICES=s3
         - AWS_DEFAULT_REGION=ap-northeast-1
         - AWS_ACCESS_KEY_ID=test
         - AWS_SECRET_ACCESS_KEY=test
         - DEBUG=0
   nginx:
      container_name: pdf-service-nginx
      tty: true
      image: nginx:latest
      ports:
         - "81:80"
      depends_on:
         - node-app
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
   mongo:
      container_name: pdf-service-mongo
      tty: true
      image: mongo:latest
      environment:
         - MONGO_INITDB_ROOT_USERNAME=root
         - MONGO_INITDB_ROOT_PASSWORD=password
      volumes:
         - ./mongo-data:/data/db
         - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
   redis:
    container_name: pdf-service-redis
    tty: true
    image: redis:latest
    ports:
        - "6379:6379"
    command: redis-server --loglevel verbose
    volumes:
      - ./redis-data:/data
   node-app:
      build: .
      container_name: pdf-service-api
      environment:
         - MONGODB_URI=mongodb://root:password@mongo:27017/history_db?authSource=admin
      stdin_open: true
      command: pm2-runtime start server.js
      ports:
         - "8001:8000"
      volumes:
         - ./output:/output
      depends_on:
         - mongo
         - redis
         - ministack
