version: '3.3'
services:
   nginx:
      container_name: pdf-service-nginx
      tty: true
      image: nginx:latest
      ports:
         - "81:80"
      depends_on:
         - node-app
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
   mongo:
      container_name: pdf-service-mongo
      tty: true
      image: mongo:latest
      environment:
         - MONGO_INITDB_ROOT_USERNAME=root
         - MONGO_INITDB_ROOT_PASSWORD=password
      volumes:
         - ./mongo-data:/data/db
         - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
   redis:
    tty: true
    image: redis:latest
    ports:
        - "6379:6379"
    command: redis-server --loglevel verbose
    volumes:
      - ./redis-data:/data
   node-app:
      build: .
      container_name: pdf-service-api
      environment:
         - MONGODB_URI=mongodb://root:password@mongo:27017/history_db?authSource=admin
      stdin_open: true
      command: pm2-runtime start server.js
      ports:
         - "8001:8000"
      volumes:
         - ./output:/output
      depends_on:
         - mongo
         - redis
